### ISSUE TITLE
Show CLI output on successful run

### ISSUE THREAD

**Issue by XhmikosR** [sindresorhus/grunt-eslint#42]
Maybe like grunt-contrib-jshint does it:

>Running "jshint:src" (jshint) task
 >> 5 files lint free.

I'll see if I can make a PR, unless someone beats me to it.

**Comment by sindresorhus** [comment]
#41 is now fixed, so PR welcome :)

**Comment by mikehaas763** [comment]
I recently started using eslint with my automatic watching dev workflow and noticed it wasn't immediately obvious once I've fixed an eslint error. So I searched and found this. This feature is still not implemented correct?

**Comment by XhmikosR** [comment]
Yeah, I had totally forgotten about this. Not sure if/when I'll have the time to have a look at it :/

**Comment by mikehaas763** [comment]
Ok. I'll wait a while and see if any of the core contributors know if any work has already been started on this. If not then I'll probably implement it depending on how easy the code base is to work with :smile:

**Comment by mikehaas763** [comment]
Well. I thought I was on the eslint repository, not the grunt plugin. Do you know if eslint directly can output a successful message?

**Comment by XhmikosR** [comment]
I don't think it does either.

**Comment by mikehaas763** [comment]
Although probably easiest to just implement something around it like in this grunt plugin to write a success message it really probably belongs directly in eslint. If eslint writes lint errors directly than there is not reason it can't write success messages directly. I'll bring this up with eslint directly.

**Comment by oliviertassinari** [comment]
:+1:

**Comment by IanVS** [comment]
This is an old issue, but just to point out, it's been discussed and decided against at ESLint in https://github.com/eslint/eslint/issues/3495.

**Comment by IanVS** [comment]
@sindresorhus Is this still an enhancement you're willing to accept a PR for?

**Comment by sindresorhus** [comment]
Nah, I prefer quiet on success. You could always use https://github.com/sindresorhus/grunt-debug-files or something if you absolutely need to know the file count, but it's not something that should be in every grunt task.

**Comment by mzgol** [comment]
I've reported a similar issue before: https://github.com/sindresorhus/grunt-eslint/issues/19 (it was blocked on some ESLint issue) and the rationale from it still stands; printing no output on success makes for broken source that goes unnoticed because a task misconfiguration, directory structure refactor etc. makes ESLint to not catch any files. If no number is printed and the task succeeds it's very easy to not notice.

Even if the task failed on 0 files linted, it'd still be important. If I'm linting 500 files and a config mistake makes ESLint to check only one of them, I'll live not knowing my code is not linted properly anymore.

BTW, @sindresorhus, you were more open to adding it in #19. ;)

**Comment by maciejsikora** [comment]
I think that success message should be there. Developer is fighting to fix any warning and issues, problems counter is smaller and smaller... and nothing. Some "0 problems" should be there or 'Your code passed', if no message exists, developer can't see if eslint checked code or not. For me after fixing 200 warnings it is disappointing that no success message appeared.

**Comment by tandrewnichols** [comment]
Or maybe an option to that affect?

```
options: {
  verboseSuccess: true
}
```

That way people who like it quiet can still have it quiet by default.

**Comment by jdforrester** [comment]
OK, so… are you expecting us to fork the package to provide a linter that works like all the others?
